[package]
name    = "startinpy"
version = "0.9.0"
authors = ["Hugo Ledoux <h.ledoux@tudelft.nl>"]
license = "MIT"
homepage="https://github.com/hugoledoux/startinpy"
repository="https://github.com/hugoledoux/startinpy"
description = "A Delaunay triangulator for terrains"
readme = "README.md"
edition = "2021"


[dependencies]
startin = ">=0.5.0"
# startin = { path = "../startin" }
# startin = { git = "https://github.com/hugoledoux/startin", branch = "develop" }
las = { version = "~0.7", features = ["laz"] }
numpy = "~0.16"
# gdal = "~0.12"
gdal = { version = "~0.12", features = ["bindgen"] }


[dependencies.pyo3]
version = "~0.16.0"
features = ["extension-module"]


[lib]
name = "startinpy"
crate-type = ["cdylib"]


[package.metadata.maturin]
requires-python = ">=3.7"
requires-dist = ["toml>=0.10.2"]
classifier=["License :: OSI Approved :: MIT License"]
