name: Build docs

on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install GDAL
      run: |
        sudo add-apt-repository -y ppa:ubuntugis/ppa
        sudo apt update
        sudo apt install gdal-bin python-gdal python3-gdal
    - uses: actions/checkout@v2


