name: Build Python bindings

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 6 * * 1' # Run every monday at 06:00 UTC

jobs:


  macos-p39:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install aarch64-apple-darwin toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: build
        args: --release --sdist -i python3.9


  win-p39:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: build
        args: --release --sdist -i python3.9

